{% set name = "awslogs" %}
{% set version = "0.15.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 19f223bb1c0703cea0689d94b1d293006529095e6ab8971f6b52289a2e545dd5

build:
  number: 0
  noarch: python
  entry_points:
    - awslogs = awslogs.bin:main
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.8
  run:
    - boto3 >=1.34.75
    - jmespath >=1.0.1
    - python >=3.8
    - python-dateutil >=2.9.0
    - termcolor >=2.4.0

test:
  imports:
    - awslogs
  commands:
    - awslogs --help

about:
  home: https://github.com/jorgebastida/awslogs
  license: BSD-3-Clause
  license_family: BSD
  license_file: COPYING
  summary: awslogs is a simple command line tool to read aws cloudwatch logs.

extra:
  recipe-maintainers:
    - setu4993
