{% set name = "awslogs" %}
{% set version = "0.13.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: f46571ebc937b3bb3e15b18545f124054386d2b03cbc852e44233aebe3350ebf

build:
  number: 0
  noarch: python
  entry_points:
    - awslogs = awslogs.bin:main
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python
  run:
    - boto3 >=1.2.1
    - jmespath >=0.7.1,<1.0.0
    - python
    - python-dateutil >=2.4.0
    - setuptools
    - termcolor >=1.1.0

test:
  imports:
    - awslogs
  commands:
    - awslogs --help

about:
  home: https://github.com/jorgebastida/awslogs
  license: BSD-3-Clause
  license_family: BSD
  license_file: COPYING
  summary: awslogs is a simple command line tool to read aws cloudwatch logs.

extra:
  recipe-maintainers:
    - setu4993
